apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:10.4.3-ce.0
        imagePullPolicy: Always
        env:
        - name: TZ
          value: $TIMEZONE
        - name: GITLAB_TIMEZONE
          value: $GITLAB_TIMEZONE
        - name: DEBUG
          value: "false"

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: P26qS5+Csz50Dkd0DLM2oN9owVBFg0PB
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: KVaMTKLAIElEp0s4L02c1O9JCP0Rfapb
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: nXJJ358Qnci0yF9qpAsLrF2vImaoFR03

        - name: GITLAB_ROOT_PASSWORD
          value: $GITLAB_ROOT_PASSWORD
        - name: GITLAB_ROOT_EMAIL
          value: $GITLAB_ROOT_EMAIL

        - name: GITLAB_HOST
          value: $GITLAB_HOST
        - name: GITLAB_PORT
          value: "$GITLAB_PORT"
        - name: GITLAB_SSH_HOST
          value: "$GITLAB_SSH_HOST"
        - name: GITLAB_SSH_PORT
          value: "$GITLAB_SSH_PORT"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: GITLAB_DATABASE_ADAPTER
          value: "$GITLAB_DATABASE_ADAPTER"
        - name: GITLAB_DATABASE_HOST
          value: "$GITLAB_DATABASE_HOST"
        - name: GITLAB_DATABASE_PORT
          value: "$GITLAB_DATABASE_PORT"
        - name: GITLAB_DATABASE_USERNAME
          value: "$GITLAB_DATABASE_USERNAME"
        - name: GITLAB_DATABASE_PASSWORD
          value: "$GITLAB_DATABASE_PASSWORD"
        - name: GITLAB_DATABASE_DATABASE
          value: "$GITLAB_DATABASE_DATABASE"

        - name: REDIS_HOST
          value: gitlab-redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_DOMAIN
          value: ""
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASS
          value: ""
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22

        livenessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
          - mountPath: /etc/gitlab
            name: gitlab-persistent-storage
          - mountPath: /var/opt/gitlab
            name: gitlab-persistent-storage
          - mountPath: /home/git/data
            name: gitlab-persistent-storage
      volumes:
      - name: gitlab-persistent-storage
        persistentVolumeClaim:
          claimName: gitlab-persistent-storage
